# Generated by Django 3.2.7 on 2021-10-08 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=256)),
                ('trade_role', models.CharField(default='', max_length=256)),
                ('free_trail', models.CharField(default='', max_length=256)),
                ('terms_and_condition', models.TextField(default='')),
                ('website', models.TextField(default='')),
                ('annual_revenue', models.FloatField(default=0.0)),
                ('total_employees', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=256)),
                ('hq_address', models.CharField(default='', max_length=256)),
                ('socialLink', models.TextField(default='')),
                ('company_contact', models.CharField(default='', max_length=256)),
                ('sales_dept_email', models.CharField(default='', max_length=256)),
                ('sales_dept_contact', models.CharField(default='', max_length=256)),
                ('license_no', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
