# Generated by Django 3.2.7 on 2021-10-12 16:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='socialLink',
            new_name='social_link1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=core.models.productFile),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_link2',
            field=models.TextField(default=''),
        ),
    ]
