# Generated by Django 3.2.7 on 2021-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211021_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
