# Generated by Django 3.2.7 on 2021-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211022_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, default=0, max_length=256, null=True),
        ),
    ]
