# Generated by Django 3.2.7 on 2021-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_company_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('large', 'LARGE'), ('medium', 'MEDIUM'), ('small', 'SMALL')], default=0, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_establishment',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
