# Generated by Django 3.2.7 on 2021-10-27 05:06

from django.db import migrations
from django.contrib.postgres import operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_forgot_password'),
    ]

    operations = [
        # operations.TrigramExtension(),
    ]
