# Generated by Django 3.2.7 on 2021-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fuzzy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check_login_attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
