# Generated by Django 3.2.7 on 2021-11-08 13:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_check_login_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_publication', models.CharField(default=0, max_length=256)),
                ('docfile', models.FileField(upload_to=core.models.PublicationFile)),
            ],
        ),
    ]
