# Generated by Django 3.2.7 on 2021-11-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.publication'),
        ),
    ]
