# Generated by Django 3.2.7 on 2021-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='field_of_work',
            field=models.CharField(blank=True, choices=[('real estate', 'Real Estate'), ('clothing', 'Clothing'), ('construction', 'Construction'), ('Installation, repair and maintenance', 'Installation, repair and maintenance')], max_length=256, null=True),
        ),
    ]
