# Generated by Django 3.2.7 on 2021-12-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_addservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
